# set the base image: Python v2.7
FROM python:2.7

# set a key-value label for the Docker image
LABEL maintainer="Klaus Allwicher"

# copy files all all sub directories to the
# `/app` directory in the container
COPY ./techtrends/ /app/

#  defines the working directory within the container
WORKDIR /app

# run commands within the container. 
# Install dependencies defined in the requirements.txt file.
RUN pip install -r requirements.txt && python init_db.py

# Start the `app.py` application.
CMD [ "python", "app.py" ]
EXPOSE 3111